// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpjrfubwmjuvgkqcjqbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwanJmdWJ3bWp1dmdrcWNqcWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Mzc4ODQsImV4cCI6MjA2OTQxMzg4NH0.m-eL_n55PZZVYa6DXW9F7Kp4JEk9djd3d69LmsTX3Zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});